title: Vishnu Manasa Devagiri
author: Vishnu Manasa Devagiri
email: vishnu.manasa.devagiri@bth.se
location: Karlskrona, Sweden
skin: Daylight

plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
