plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

remote_theme: ngzhio/jekyll-theme-hamilton

title: Vishnu Manasa Devagiri
author: Vishnu Manasa Devagiri
email: vishnu.manasa.devagiri@bth.se
location: Karlskrona, Sweden
logo: logo.png

# skin: Daylight

exclude:
  - README.md
