title: Vishnu Manasa Devagiri
author: Vishnu Manasa Devagiri
email: vishnu.manasa.devagiri@bth.se
location: Karlskrona, Sweden
avatar: /logo.jpeg
subscribe: false

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

remote_theme: ngzhio/jekyll-theme-hamilton

# skin: Daylight

exclude:
  - README.md

logo: /logo
